DROP TABLE SALESITEM_PRODUCT_TREATMENT
GO

DROP TABLE CUSTOMER
GO

CREATE TABLE CUSTOMER (
    PK_CustomerId INT IDENTITY(1,1) PRIMARY KEY,
    FirstName NVARCHAR(50) NOT NULL,
	LastName NVarChar (50) NOT NULL,
    Address NVARCHAR(100) NOT NULL,
    Phone NVARCHAR(10) NOT NULL,
    Email NVARCHAR(100) NOT NULL
   );
GO

CREATE TABLE SALESITEM_PRODUCT_TREATMENT (
PK_SalesItemId_Product_Treatment INT IDENTITY(1,1) PRIMARY KEY,
Category NVarChar(50) NOT NULL,
Type NVarChar(50) NOT NULL,
Name NVarChar(100) NOT NULL,
Description NVarChar(MAX) NOT NULL,
Price Decimal NOT NULL,
);
GO